# Generated by Django 4.2 on 2023-04-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_username_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, '선택'), ('M', '남성'), ('W', '여성'), ('N', '선택하지 않음')], default='선택', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
