# Generated by Django 4.2 on 2023-04-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('W', '여성'), ('N', '선택하지 않음')], default='N', max_length=7),
        ),
    ]
